title: Abdul A # your name (or website title) here
logo: "/IMG_2346.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a data science enthusiast with a blend of business acumen, analytics, and advanced management skills. 
  <br><br>
  Skills: Python(Pandas,Seaborn, Matplotlib, and Numpy),R,Tablueau, SQL 
  <br><br>
  <a href="https://www.linkedin.com/in/abdulrahman-aroworamimo-02213514b">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
