title: <p align="center"> Abdulrahman Aroworamimo </p>
logo: "/images/IMG_4539.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a data scientist with a unique blend of business acumen, analytics, and advanced management skills. I am looking to apply my skills to solve problems in pharma and healthcare individually and within a team.
  <br>
  Skills: Python(Pandas,Seaborn,Scikit-learn, Gurobi, Matplotlib, and Numpy),R,Tableau, SQL 
  <br>
  <a href="https://www.linkedin.com/in/abdulrahman-aroworamimo-02213514b">View My LinkedIn Profile</a> 

# Adjust the width and height of the photo here
<style>
  .logo {
    max-width: 300px; /* Set the maximum width of the photo */
    height: auto; /* Maintain aspect ratio */
    display: block; /* Center the image */
    margin: 0 auto; /* Center the image */
    border-radius: 50%; /* Make the image rounded */
  }
</style>

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
