title: <p align="center"> Abdulrahman Aroworamimo </p>

logo: "/images/IMG_2346.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/abdulrahman-aroworamimo-02213514b">LinkedIn</a> 
  </p>
  
  <p align="justify">
  I am a data science enthusiast with a blend of business acumen, analytics, and advanced management skills. 
  <br><br>
  Skills: Python(Pandas,Seaborn, Matplotlib, and Numpy),R,Tablueau, SQL 
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking IDtitle:<p align="center"> Abdulrahman Aroworamimo </p> # your name (or website title) here
